easy_admin:
    site_name: 'Ma super admin'
    entities:
        Author:
            class: App\Entity\Author
            label: 'Auteur'
            list:
                title: 'Liste des auteurs'

        Book:
            class: App\Entity\Book
            label: 'Livres'
            list:
                fields:
                    - { property: 'title'}
                    - { property: 'image', type: 'image', base_path: '%app.path.uploads_dir%'}

        Box:
            class: App\Entity\Box
            label: 'Boites'
            list:
            title: 'Liste des boites'

        Borrow:
            class: App\Entity\Borrow
            label: 'Boites'
            list:
            title: 'Liste des boites'


        Category:
            class: App\Entity\Category
            label: 'Catégories'
            list:
            title: 'Liste des catégories'

        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
            title: 'Liste des Utilisateurs'